# Generated by Django 3.2.7 on 2021-09-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-created',), 'verbose_name': 'story', 'verbose_name_plural': 'stories'},
        ),
        migrations.AlterField(
            model_name='story',
            name='cover',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='picture'),
        ),
        migrations.AlterField(
            model_name='story',
            name='sound',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='music'),
        ),
    ]
